name: fit_timesheets
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  searchable_dropdown: ^1.1.3
  flutter_spinbox: ^0.3.0
  flutter_speed_dial: ^3.0.5
  toast: ^0.1.5
  unicorndial: ^1.1.5
  animated_text_kit: ^4.2.1
  animated_splash: ^1.0.0
  flutter_rounded_date_picker: ^2.0.2
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications:

  device_info: ^2.0.0
  flutter_native_timezone: ^1.0.10
  percent_indicator: "^2.1.7+2"
  animated_textformfields: ^1.0.1
  whatsapp_unilink: ^2.0.0
  rxdart: ^0.26.0-nullsafety.1
  shared_preferences: ^2.0.1
  flutter_ringtone_player: ^3.0.0
  screenshot: ^0.2.0
  share: ^0.6.5+4
  filter_list: ^0.0.7
  syncfusion_flutter_pdf: ^18.4.39-beta
  image_picker: ^0.6.6+5
  flutter_spinkit: ^4.1.2
  custom_navigation_drawer: ^0.0.1
  matrix4_transform: ^1.1.5
  multi_select_item: ^1.0.3
  circular_menu:
  custom_splash: ^0.0.2
  curved_navigation_bar: ^0.3.2
  fab_circular_menu: ^1.0.0
  draggable_floating_action_button: ^0.0.5
  slimy_card: ^1.0.4
  flutter_progress_button: ^1.0.0
  toggle_switch: "^0.1.4"
  font_awesome_flutter: ^8.7.0
  geolocator: ^5.3.1
  intl_phone_field: ^2.0.0
  geocoder: ^0.2.1
  flutter_fluid_slider: ^1.0.2
  flutter_score_slider: ^1.0.1
  flutter_xlider: 3.4.0-dev.3
  permission_handler:
  flutter_html_to_pdf: ^0.6.1
  provider:
  open_file: ^3.1.0
  pdf: ^1.5.0
  confetti: ^0.5.4+1
  flutter_full_pdf_viewer: ^1.0.6
  image_gallery_saver:
  dio: ^3.0.10
  binary: ^2.0.0

  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/fitlogo.jpg
    - assets/icons/aoo.png
    - assets/icons/pen.png
    - assets/icons/pending.png
    - assets/icons/submitted.png
    - assets/lang/en.json
    - assets/lang/km.json
    - assets/images/fitlogo.jpg
    - assets/icons/add.jpg
    - assets/icons/approval.jpg
    - assets/icons/changepassword.png
    - assets/icons/logout.jpg
    - assets/icons/password.jpg
    - assets/icons/profile.jpg
    - assets/icons/avatar.jpg
    - assets/icons/fb.jpg
    - assets/icons/mail.jpg
    - assets/icons/insta.icon.jpg
    - assets/icons/whatsapp.jpg
    - assets/icons/twitter.jpg
    - assets/images/logoutt.png
    - assets/images/passchange.png
    - assets/images/addreimb.png
    - assets/images/approval.png
    - assets/icons/passchange2.png
    - assets/icons/changee.jpg
    - assets/images/passs.png
    - assets/icons/ss.png
    - assets/icons/share.png
    - assets/icons/share1.png
    - assets/icons/share3.png
    - assets/images/reject.png
    - assets/images/appro.png
    - assets/images/confirm.png
    - assets/images/cancel.png
    - assets/images/pdf.png
    - assets/icons/share4.png
    - assets/fitlogo.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster-Regular
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: DancingScript-VariableFont_wght
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
    - family: Pacifico-Regular
      fonts:
          - asset: assets/fonts/Pacifico-Regular.ttf
    - family: JosefinSans-VariableFont_wght
      fonts:
          - asset: assets/fonts/JosefinSans-VariableFont_wght.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
